const skinData = [
    "AK-47 | Aquamarine Revenge",
    "AK-47 | Asiimov",
    "AK-47 | Baroque Purple",
    "AK-47 | Black Laminate",
    "AK-47 | Bloodsport",
    "AK-47 | Blue Laminate",
    "AK-47 | Cartel",
    "AK-47 | Case Hardened",
    "AK-47 | Elite Build",
    "AK-47 | Emerald Pinstripe",
    "AK-47 | Fire Serpent",
    "AK-47 | First Class",
    "AK-47 | Frontside Misty",
    "AK-47 | Fuel Injector",
    "AK-47 | Gold Arabesque",
    "AK-47 | Green Laminate",
    "AK-47 | Head Shot",
    "AK-47 | Hydroponic",
    "AK-47 | Ice Coaled",
    "AK-47 | Jaguar",
    "AK-47 | Jet Set",
    "AK-47 | Jungle Spray",
    "AK-47 | Leet Museo",
    "AK-47 | Legion of Anubis",
    "AK-47 | Neon Revolution",
    "AK-47 | Neon Rider",
    "AK-47 | Nightwish",
    "AK-47 | Orbit Mk01",
    "AK-47 | Panthera onca",
    "AK-47 | Phantom Disruptor",
    "AK-47 | Point Disarray",
    "AK-47 | Predator",
    "AK-47 | Rat Rod",
    "AK-47 | Red Laminate",
    "AK-47 | Safari Mesh",
    "AK-47 | Safety Net",
    "AK-47 | Slate",
    "AK-47 | Steel Delta",
    "AK-47 | The Empress",
    "AK-47 | Uncharted",
    "AK-47 | Vulcan",
    "AK-47 | Wasteland Rebel",
    "AK-47 | Wild Lotus",
    "AK-47 | X-Ray",
    "AUG | Akihabara Accept",
    "AUG | Amber Fade",
    "AUG | Amber Slipstream",
    "AUG | Anodized Navy",
    "AUG | Arctic Wolf",
    "AUG | Aristocrat",
    "AUG | Bengal Tiger",
    "AUG | Carved Jade",
    "AUG | Chameleon",
    "AUG | Colony",
    "AUG | Condemned",
    "AUG | Contractor",
    "AUG | Daedalus",
    "AUG | Death by Puppy",
    "AUG | Flame Jörmungandr",
    "AUG | Fleet Flock",
    "AUG | Hot Rod",
    "AUG | Midnight Lily",
    "AUG | Momentum",
    "AUG | Navy Murano",
    "AUG | Plague",
    "AUG | Radiation Hazard",
    "AUG | Random Access",
    "AUG | Ricochet",
    "AUG | Sand Storm",
    "AUG | Snake Pit",
    "AUG | Spalted Wood",
    "AUG | Storm",
    "AUG | Stymphalian",
    "AUG | Surveillance",
    "AUG | Sweeper",
    "AUG | Syd Mead",
    "AUG | Tom Cat",
    "AUG | Torque",
    "AUG | Triqua",
    "AUG | Wings",
    "AWP | Acheron",
    "AWP | Atheris",
    "AWP | BOOM",
    "AWP | Black Nile",
    "AWP | Capillary",
    "AWP | Chromatic Aberration",
    "AWP | Containment Breach",
    "AWP | Corticera",
    "AWP | Desert Hydra",
    "AWP | Dragon Lore",
    "AWP | Duality",
    "AWP | Electric Hive",
    "AWP | Elite Build",
    "AWP | Exoskeleton",
    "AWP | Fade",
    "AWP | Fever Dream",
    "AWP | Graphite",
    "AWP | Gungnir",
    "AWP | Hyper Beast",
    "AWP | Lightning Strike",
    "AWP | Medusa",
    "AWP | Mortis",
    "AWP | Neo-Noir",
    "AWP | Oni Taiji",
    "AWP | PAW",
    "AWP | POP AWP",
    "AWP | Phobos",
    "AWP | Pink DDPAT",
    "AWP | Safari Mesh",
    "AWP | Silk Tiger",
    "AWP | Snake Camo",
    "AWP | Sun in Leo",
    "AWP | The Prince",
    "AWP | Wildfire",
    "AWP | Worm God",
    "CZ75-Auto | Army Sheen",
    "CZ75-Auto | Chalice",
    "CZ75-Auto | Circaetus",
    "CZ75-Auto | Crimson Web",
    "CZ75-Auto | Distressed",
    "CZ75-Auto | Eco",
    "CZ75-Auto | Emerald",
    "CZ75-Auto | Emerald Quartz",
    "CZ75-Auto | Framework",
    "CZ75-Auto | Green Plaid",
    "CZ75-Auto | Hexane",
    "CZ75-Auto | Imprint",
    "CZ75-Auto | Indigo",
    "CZ75-Auto | Jungle Dashed",
    "CZ75-Auto | Midnight Palm",
    "CZ75-Auto | Nitro",
    "CZ75-Auto | Poison Dart",
    "CZ75-Auto | Pole Position",
    "CZ75-Auto | Polymer",
    "CZ75-Auto | Red Astor",
    "CZ75-Auto | Silver",
    "CZ75-Auto | Syndicate",
    "CZ75-Auto | Tacticat",
    "CZ75-Auto | The Fuschia Is Now",
    "CZ75-Auto | Tigris",
    "CZ75-Auto | Tread Plate",
    "CZ75-Auto | Tuxedo",
    "CZ75-Auto | Twist",
    "CZ75-Auto | Vendetta",
    "CZ75-Auto | Victoria",
    "CZ75-Auto | Xiangliu",
    "CZ75-Auto | Yellow Jacket",
    "Desert Eagle | Blaze",
    "Desert Eagle | Blue Ply",
    "Desert Eagle | Bronze Deco",
    "Desert Eagle | Cobalt Disruption",
    "Desert Eagle | Code Red",
    "Desert Eagle | Conspiracy",
    "Desert Eagle | Corinthian",
    "Desert Eagle | Crimson Web",
    "Desert Eagle | Directive",
    "Desert Eagle | Emerald Jörmungandr",
    "Desert Eagle | Fennec Fox",
    "Desert Eagle | Golden Koi",
    "Desert Eagle | Hand Cannon",
    "Desert Eagle | Heirloom",
    "Desert Eagle | Hypnotic",
    "Desert Eagle | Kumicho Dragon",
    "Desert Eagle | Light Rail",
    "Desert Eagle | Mecha Industries",
    "Desert Eagle | Meteorite",
    "Desert Eagle | Midnight Storm",
    "Desert Eagle | Mudder",
    "Desert Eagle | Naga",
    "Desert Eagle | Night",
    "Desert Eagle | Night Heist",
    "Desert Eagle | Ocean Drive",
    "Desert Eagle | Oxide Blaze",
    "Desert Eagle | Pilot",
    "Desert Eagle | Printstream",
    "Desert Eagle | Sputnik",
    "Desert Eagle | Sunset Storm 壱",
    "Desert Eagle | Sunset Storm 弐",
    "Desert Eagle | The Bronze",
    "Desert Eagle | Trigger Discipline",
    "Desert Eagle | Urban DDPAT",
    "Desert Eagle | Urban Rubble",
    "Dual Berettas | Anodized Navy",
    "Dual Berettas | Balance",
    "Dual Berettas | Black Limba",
    "Dual Berettas | Briar",
    "Dual Berettas | Cartel",
    "Dual Berettas | Cobalt Quartz",
    "Dual Berettas | Cobra Strike",
    "Dual Berettas | Colony",
    "Dual Berettas | Contractor",
    "Dual Berettas | Dezastre",
    "Dual Berettas | Drift Wood",
    "Dual Berettas | Dualing Dragons",
    "Dual Berettas | Duelist",
    "Dual Berettas | Elite 1.6",
    "Dual Berettas | Emerald",
    "Dual Berettas | Flora Carnivora",
    "Dual Berettas | Heist",
    "Dual Berettas | Hemoglobin",
    "Dual Berettas | Marina",
    "Dual Berettas | Melondrama",
    "Dual Berettas | Moon in Libra",
    "Dual Berettas | Oil Change",
    "Dual Berettas | Panther",
    "Dual Berettas | Pyre",
    "Dual Berettas | Retribution",
    "Dual Berettas | Royal Consorts",
    "Dual Berettas | Shred",
    "Dual Berettas | Stained",
    "Dual Berettas | Switch Board",
    "Dual Berettas | Tread",
    "Dual Berettas | Twin Turbo",
    "Dual Berettas | Urban Shock",
    "Dual Berettas | Ventilators",
    "FAMAS | Afterimage",
    "FAMAS | CaliCamo",
    "FAMAS | Colony",
    "FAMAS | Commemoration",
    "FAMAS | Contrast Spray",
    "FAMAS | Crypsis",
    "FAMAS | Cyanospatter",
    "FAMAS | Decommissioned",
    "FAMAS | Djinn",
    "FAMAS | Eye of Athena",
    "FAMAS | Faulty Wiring",
    "FAMAS | Hexane",
    "FAMAS | Macabre",
    "FAMAS | Mecha Industries",
    "FAMAS | Meltdown",
    "FAMAS | Meow 36",
    "FAMAS | Neural Net",
    "FAMAS | Night Borre",
    "FAMAS | Prime Conspiracy",
    "FAMAS | Pulse",
    "FAMAS | Rapid Eye Movement",
    "FAMAS | Roll Cage",
    "FAMAS | Spitfire",
    "FAMAS | Styx",
    "FAMAS | Sundown",
    "FAMAS | Survivor Z",
    "FAMAS | Teardown",
    "FAMAS | Valence",
    "FAMAS | Waters of Nephthys",
    "FAMAS | ZX Spectron",
    "Five-SeveN | Angry Mob",
    "Five-SeveN | Anodized Gunmetal",
    "Five-SeveN | Berries And Cherries",
    "Five-SeveN | Boost Protocol",
    "Five-SeveN | Buddy",
    "Five-SeveN | Candy Apple",
    "Five-SeveN | Capillary",
    "Five-SeveN | Case Hardened",
    "Five-SeveN | Contractor",
    "Five-SeveN | Coolant",
    "Five-SeveN | Copper Galaxy",
    "Five-SeveN | Crimson Blossom",
    "Five-SeveN | Fairy Tale",
    "Five-SeveN | Fall Hazard",
    "Five-SeveN | Flame Test",
    "Five-SeveN | Forest Night",
    "Five-SeveN | Fowl Play",
    "Five-SeveN | Hot Shot",
    "Five-SeveN | Hyper Beast",
    "Five-SeveN | Jungle",
    "Five-SeveN | Kami",
    "Five-SeveN | Neon Kimono",
    "Five-SeveN | Nightshade",
    "Five-SeveN | Nitro",
    "Five-SeveN | Orange Peel",
    "Five-SeveN | Retrobution",
    "Five-SeveN | Scrawl",
    "Five-SeveN | Scumbria",
    "Five-SeveN | Silver Quartz",
    "Five-SeveN | Triumvirate",
    "Five-SeveN | Urban Hazard",
    "Five-SeveN | Violent Daimyo",
    "Five-SeveN | Withered Vine",
    "G3SG1 | Ancient Ritual",
    "G3SG1 | Arctic Camo",
    "G3SG1 | Azure Zebra",
    "G3SG1 | Black Sand",
    "G3SG1 | Chronos",
    "G3SG1 | Contractor",
    "G3SG1 | Demeter",
    "G3SG1 | Desert Storm",
    "G3SG1 | Digital Mesh",
    "G3SG1 | Dream Glade",
    "G3SG1 | Flux",
    "G3SG1 | Green Apple",
    "G3SG1 | High Seas",
    "G3SG1 | Hunter",
    "G3SG1 | Jungle Dashed",
    "G3SG1 | Keeping Tabs",
    "G3SG1 | Murky",
    "G3SG1 | New Roots",
    "G3SG1 | Orange Crash",
    "G3SG1 | Orange Kimono",
    "G3SG1 | Polar Camo",
    "G3SG1 | Safari Mesh",
    "G3SG1 | Scavenger",
    "G3SG1 | Stinger",
    "G3SG1 | VariCamo",
    "G3SG1 | Ventilator",
    "G3SG1 | Violet Murano",
    "Galil AR | Akoben",
    "Galil AR | Amber Fade",
    "Galil AR | Aqua Terrace",
    "Galil AR | Black Sand",
    "Galil AR | Blue Titanium",
    "Galil AR | CAUTION!",
    "Galil AR | Cerberus",
    "Galil AR | Chromatic Aberration",
    "Galil AR | Cold Fusion",
    "Galil AR | Connexion",
    "Galil AR | Crimson Tsunami",
    "Galil AR | Destroyer",
    "Galil AR | Dusk Ruins",
    "Galil AR | Firefight",
    "Galil AR | Hunting Blind",
    "Galil AR | Kami",
    "Galil AR | Orange DDPAT",
    "Galil AR | Phoenix Blacklight",
    "Galil AR | Rocket Pop",
    "Galil AR | Sage Spray",
    "Galil AR | Shattered",
    "Galil AR | Signal",
    "Galil AR | Stone Cold",
    "Galil AR | Sugar Rush",
    "Galil AR | Tornado",
    "Galil AR | Tuxedo",
    "Galil AR | Urban Rubble",
    "Galil AR | Vandal",
    "Galil AR | VariCamo",
    "Galil AR | Winter Forest",
    "Glock-18 | Blue Fissure",
    "Glock-18 | Brass",
    "Glock-18 | Bullet Queen",
    "Glock-18 | Bunsen Burner",
    "Glock-18 | Candy Apple",
    "Glock-18 | Catacombs",
    "Glock-18 | Clear Polymer",
    "Glock-18 | Dragon Tattoo",
    "Glock-18 | Fade",
    "Glock-18 | Franklin",
    "Glock-18 | Gamma Doppler",
    "Glock-18 | Grinder",
    "Glock-18 | Groundwater",
    "Glock-18 | High Beam",
    "Glock-18 | Ironwork",
    "Glock-18 | Moonrise",
    "Glock-18 | Neo-Noir",
    "Glock-18 | Night",
    "Glock-18 | Nuclear Garden",
    "Glock-18 | Off World",
    "Glock-18 | Oxide Blaze",
    "Glock-18 | Pink DDPAT",
    "Glock-18 | Ramese&#39s Reach",
    "Glock-18 | Reactor",
    "Glock-18 | Red Tire",
    "Glock-18 | Royal Legion",
    "Glock-18 | Sacrifice",
    "Glock-18 | Sand Dune",
    "Glock-18 | Snack Attack",
    "Glock-18 | Steel Disruption",
    "Glock-18 | Synth Leaf",
    "Glock-18 | Twilight Galaxy",
    "Glock-18 | Umbral Rabbit",
    "Glock-18 | Vogue",
    "Glock-18 | Warhawk",
    "Glock-18 | Wasteland Rebel",
    "Glock-18 | Water Elemental",
    "Glock-18 | Weasel",
    "Glock-18 | Winterized",
    "Glock-18 | Wraiths",
    "M249 | Aztec",
    "M249 | Blizzard Marbleized",
    "M249 | Contrast Spray",
    "M249 | Deep Relief",
    "M249 | Downtown",
    "M249 | Emerald Poison Dart",
    "M249 | Gator Mesh",
    "M249 | Humidor",
    "M249 | Impact Drill",
    "M249 | Jungle",
    "M249 | Jungle DDPAT",
    "M249 | Magma",
    "M249 | Midnight Palm",
    "M249 | Nebula Crusader",
    "M249 | O.S.I.P.R.",
    "M249 | Predator",
    "M249 | Shipping Forecast",
    "M249 | Spectre",
    "M249 | Submerged",
    "M249 | System Lock",
    "M249 | Warbird",
    "M4A1-S | Atomic Alloy",
    "M4A1-S | Basilisk",
    "M4A1-S | Blood Tiger",
    "M4A1-S | Blue Phosphor",
    "M4A1-S | Boreal Forest",
    "M4A1-S | Briefing",
    "M4A1-S | Chantico&#39s Fire",
    "M4A1-S | Control Panel",
    "M4A1-S | Cyrex",
    "M4A1-S | Decimator",
    "M4A1-S | Emphorosaur-S",
    "M4A1-S | Fizzy POP",
    "M4A1-S | Flashback",
    "M4A1-S | Golden Coil",
    "M4A1-S | Guardian",
    "M4A1-S | Hot Rod",
    "M4A1-S | Hyper Beast",
    "M4A1-S | Icarus Fell",
    "M4A1-S | Imminent Danger",
    "M4A1-S | Knight",
    "M4A1-S | Leaded Glass",
    "M4A1-S | Master Piece",
    "M4A1-S | Mecha Industries",
    "M4A1-S | Moss Quartz",
    "M4A1-S | Mud-Spec",
    "M4A1-S | Night Terror",
    "M4A1-S | Nightmare",
    "M4A1-S | Nitro",
    "M4A1-S | Player Two",
    "M4A1-S | Printstream",
    "M4A1-S | VariCamo",
    "M4A1-S | Welcome to the Jungle",
    "M4A4 | Bullet Rain",
    "M4A4 | Buzz Kill",
    "M4A4 | Converter",
    "M4A4 | Cyber Security",
    "M4A4 | Dark Blossom",
    "M4A4 | Daybreak",
    "M4A4 | Desert Storm",
    "M4A4 | Desert-Strike",
    "M4A4 | Desolate Space",
    "M4A4 | Evil Daimyo",
    "M4A4 | Eye of Horus",
    "M4A4 | Faded Zebra",
    "M4A4 | Global Offensive",
    "M4A4 | Griffin",
    "M4A4 | Hellfire",
    "M4A4 | Howl",
    "M4A4 | In Living Color",
    "M4A4 | Jungle Tiger",
    "M4A4 | Magnesium",
    "M4A4 | Mainframe",
    "M4A4 | Modern Hunter",
    "M4A4 | Neo-Noir",
    "M4A4 | Poly Mag",
    "M4A4 | Poseidon",
    "M4A4 | Radiation Hazard",
    "M4A4 | Red DDPAT",
    "M4A4 | Royal Paladin",
    "M4A4 | Spider Lily",
    "M4A4 | Temukau",
    "M4A4 | The Battlestar",
    "M4A4 | The Coalition",
    "M4A4 | The Emperor",
    "M4A4 | Tooth Fairy",
    "M4A4 | Tornado",
    "M4A4 | Urban DDPAT",
    "M4A4 | X-Ray",
    "M4A4 | Zirka",
    "M4A4 | 龍王",
    "MAC-10 | Allure",
    "MAC-10 | Aloha",
    "MAC-10 | Amber Fade",
    "MAC-10 | Button Masher",
    "MAC-10 | Calf Skin",
    "MAC-10 | Candy Apple",
    "MAC-10 | Carnivore",
    "MAC-10 | Case Hardened",
    "MAC-10 | Classic Crate",
    "MAC-10 | Commuter",
    "MAC-10 | Copper Borre",
    "MAC-10 | Curse",
    "MAC-10 | Disco Tech",
    "MAC-10 | Echoing Sands",
    "MAC-10 | Ensnared",
    "MAC-10 | Fade",
    "MAC-10 | Gold Brick",
    "MAC-10 | Graven",
    "MAC-10 | Heat",
    "MAC-10 | Hot Snakes",
    "MAC-10 | Indigo",
    "MAC-10 | Lapis Gator",
    "MAC-10 | Last Dive",
    "MAC-10 | Malachite",
    "MAC-10 | Monkeyflage",
    "MAC-10 | Neon Rider",
    "MAC-10 | Nuclear Garden",
    "MAC-10 | Oceanic",
    "MAC-10 | Palm",
    "MAC-10 | Pipe Down",
    "MAC-10 | Propaganda",
    "MAC-10 | Rangeen",
    "MAC-10 | Red Filigree",
    "MAC-10 | Sienna Damask",
    "MAC-10 | Silver",
    "MAC-10 | Stalker",
    "MAC-10 | Strats",
    "MAC-10 | Surfwood",
    "MAC-10 | Tatter",
    "MAC-10 | Tornado",
    "MAC-10 | Toybox",
    "MAC-10 | Ultraviolet",
    "MAC-10 | Urban DDPAT",
    "MAC-10 | Whitefish",
    "MAG-7 | BI83 Spectrum",
    "MAG-7 | Bulldozer",
    "MAG-7 | Carbon Fiber",
    "MAG-7 | Chainmail",
    "MAG-7 | Cinquedea",
    "MAG-7 | Cobalt Core",
    "MAG-7 | Copper Coated",
    "MAG-7 | Core Breach",
    "MAG-7 | Counter Terrace",
    "MAG-7 | Firestarter",
    "MAG-7 | Foresight",
    "MAG-7 | Hard Water",
    "MAG-7 | Hazard",
    "MAG-7 | Heat",
    "MAG-7 | Heaven Guard",
    "MAG-7 | Insomnia",
    "MAG-7 | Irradiated Alert",
    "MAG-7 | Justice",
    "MAG-7 | Memento",
    "MAG-7 | Metallic DDPAT",
    "MAG-7 | Monster Call",
    "MAG-7 | Navy Sheen",
    "MAG-7 | Petroglyph",
    "MAG-7 | Popdog",
    "MAG-7 | Praetorian",
    "MAG-7 | Prism Terrace",
    "MAG-7 | Rust Coat",
    "MAG-7 | SWAG-7",
    "MAG-7 | Sand Dune",
    "MAG-7 | Seabird",
    "MAG-7 | Silver",
    "MAG-7 | Sonar",
    "MAG-7 | Storm",
    "MP5-SD | Acid Wash",
    "MP5-SD | Agent",
    "MP5-SD | Autumn Twilly",
    "MP5-SD | Bamboo Garden",
    "MP5-SD | Co-Processor",
    "MP5-SD | Condition Zero",
    "MP5-SD | Desert Strike",
    "MP5-SD | Dirt Drop",
    "MP5-SD | Gauss",
    "MP5-SD | Kitbash",
    "MP5-SD | Liquidation",
    "MP5-SD | Necro Jr.",
    "MP5-SD | Nitro",
    "MP5-SD | Oxide Oasis",
    "MP5-SD | Phosphor",
    "MP7 | Abyssal Apparition",
    "MP7 | Akoben",
    "MP7 | Anodized Navy",
    "MP7 | Armor Core",
    "MP7 | Army Recon",
    "MP7 | Asterion",
    "MP7 | Bloodsport",
    "MP7 | Cirrus",
    "MP7 | Fade",
    "MP7 | Forest DDPAT",
    "MP7 | Full Stop",
    "MP7 | Groundwater",
    "MP7 | Guerrilla",
    "MP7 | Gunsmoke",
    "MP7 | Impire",
    "MP7 | Motherboard",
    "MP7 | Nemesis",
    "MP7 | Neon Ply",
    "MP7 | Ocean Foam",
    "MP7 | Olive Plaid",
    "MP7 | Orange Peel",
    "MP7 | Powercore",
    "MP7 | Prey",
    "MP7 | Scorched",
    "MP7 | Special Delivery",
    "MP7 | Sunbaked",
    "MP7 | Tall Grass",
    "MP7 | Teal Blossom",
    "MP7 | Urban Hazard",
    "MP7 | Vault Heist",
    "MP7 | Whiteout",
    "MP9 | Airlock",
    "MP9 | Army Sheen",
    "MP9 | Bioleak",
    "MP9 | Black Sand",
    "MP9 | Bulldozer",
    "MP9 | Capillary",
    "MP9 | Dark Age",
    "MP9 | Dart",
    "MP9 | Deadly Poison",
    "MP9 | Dry Season",
    "MP9 | Featherweight",
    "MP9 | Food Chain",
    "MP9 | Goo",
    "MP9 | Green Plaid",
    "MP9 | Hot Rod",
    "MP9 | Hydra",
    "MP9 | Hypnotic",
    "MP9 | Modest Threat",
    "MP9 | Mount Fuji",
    "MP9 | Music Box",
    "MP9 | Old Roots",
    "MP9 | Orange Peel",
    "MP9 | Pandora&#39s Box",
    "MP9 | Rose Iron",
    "MP9 | Ruby Poison Dart",
    "MP9 | Sand Dashed",
    "MP9 | Sand Scale",
    "MP9 | Setting Sun",
    "MP9 | Slide",
    "MP9 | Stained Glass",
    "MP9 | Starlight Protector",
    "MP9 | Storm",
    "MP9 | Wild Lily",
    "Negev | Anodized Navy",
    "Negev | Army Sheen",
    "Negev | Boroque Sand",
    "Negev | Bratatat",
    "Negev | Bulkhead",
    "Negev | CaliCamo",
    "Negev | Desert-Strike",
    "Negev | Drop Me",
    "Negev | Infrastructure",
    "Negev | Lionfish",
    "Negev | Mjölnir",
    "Negev | Nuclear Waste",
    "Negev | Palm",
    "Negev | Phoenix Stencil",
    "Negev | Power Loader",
    "Negev | Prototype",
    "Negev | Terrain",
    "Negev | Ultralight",
    "Negev | dev_texture",
    "Nova | Antique",
    "Nova | Army Sheen",
    "Nova | Baroque Orange",
    "Nova | Blaze Orange",
    "Nova | Bloomstick",
    "Nova | Caged Steel",
    "Nova | Candy Apple",
    "Nova | Clear Polymer",
    "Nova | Exo",
    "Nova | Forest Leaves",
    "Nova | Ghost Camo",
    "Nova | Gila",
    "Nova | Graphite",
    "Nova | Green Apple",
    "Nova | Hyper Beast",
    "Nova | Interlock",
    "Nova | Koi",
    "Nova | Mandrel",
    "Nova | Modern Hunter",
    "Nova | Moon in Libra",
    "Nova | Plume",
    "Nova | Polar Mesh",
    "Nova | Predator",
    "Nova | Quick Sand",
    "Nova | Ranger",
    "Nova | Red Quartz",
    "Nova | Rising Skull",
    "Nova | Rust Coat",
    "Nova | Sand Dune",
    "Nova | Sobek&#39s Bite",
    "Nova | Tempest",
    "Nova | Toy Soldier",
    "Nova | Walnut",
    "Nova | Wild Six",
    "Nova | Windblown",
    "Nova | Wood Fired",
    "P2000 | Acid Etched",
    "P2000 | Amber Fade",
    "P2000 | Chainmail",
    "P2000 | Coach Class",
    "P2000 | Corticera",
    "P2000 | Dispatch",
    "P2000 | Fire Elemental",
    "P2000 | Gnarled",
    "P2000 | Granite Marbleized",
    "P2000 | Grassland",
    "P2000 | Grassland Leaves",
    "P2000 | Handgun",
    "P2000 | Imperial",
    "P2000 | Imperial Dragon",
    "P2000 | Ivory",
    "P2000 | Lifted Spirits",
    "P2000 | Obsidian",
    "P2000 | Ocean Foam",
    "P2000 | Oceanic",
    "P2000 | Panther Camo",
    "P2000 | Pathfinder",
    "P2000 | Pulse",
    "P2000 | Red FragCam",
    "P2000 | Scorpion",
    "P2000 | Silver",
    "P2000 | Space Race",
    "P2000 | Turf",
    "P2000 | Urban Hazard",
    "P2000 | Wicked Sick",
    "P2000 | Woodsman",
    "P250 | Apep&#39s Curse",
    "P250 | Bengal Tiger",
    "P250 | Black & Tan",
    "P250 | Bone Mask",
    "P250 | Boreal Forest",
    "P250 | Cartel",
    "P250 | Cassette",
    "P250 | Contaminant",
    "P250 | Contamination",
    "P250 | Crimson Kimono",
    "P250 | Cyber Shell",
    "P250 | Dark Filigree",
    "P250 | Digital Architect",
    "P250 | Drought",
    "P250 | Exchanger",
    "P250 | Facets",
    "P250 | Facility Draft",
    "P250 | Forest Night",
    "P250 | Franklin",
    "P250 | Gunsmoke",
    "P250 | Hive",
    "P250 | Inferno",
    "P250 | Iron Clad",
    "P250 | Mehndi",
    "P250 | Metallic DDPAT",
    "P250 | Mint Kimono",
    "P250 | Modern Hunter",
    "P250 | Muertos",
    "P250 | Nevermore",
    "P250 | Nuclear Threat",
    "P250 | Re.built",
    "P250 | Red Rock",
    "P250 | Ripple",
    "P250 | Sand Dune",
    "P250 | See Ya Later",
    "P250 | Splash",
    "P250 | Steel Disruption",
    "P250 | Supernova",
    "P250 | Undertow",
    "P250 | Valence",
    "P250 | Verdigris",
    "P250 | Vino Primo",
    "P250 | Visions",
    "P250 | Whiteout",
    "P250 | Wingshot",
    "P90 | Ancient Earth",
    "P90 | Ash Wood",
    "P90 | Asiimov",
    "P90 | Astral Jörmungandr",
    "P90 | Baroque Red",
    "P90 | Blind Spot",
    "P90 | Chopper",
    "P90 | Cocoa Rampage",
    "P90 | Cold Blooded",
    "P90 | Death Grip",
    "P90 | Desert DDPAT",
    "P90 | Desert Warfare",
    "P90 | Elite Build",
    "P90 | Emerald Dragon",
    "P90 | Facility Negative",
    "P90 | Fallout Warning",
    "P90 | Freight",
    "P90 | Glacier Mesh",
    "P90 | Grim",
    "P90 | Leather",
    "P90 | Module",
    "P90 | Neoqueen",
    "P90 | Nostalgia",
    "P90 | Off World",
    "P90 | Run and Hide",
    "P90 | Sand Spray",
    "P90 | ScaraB Rush",
    "P90 | Schematic",
    "P90 | Scorched",
    "P90 | Shallow Grave",
    "P90 | Shapewood",
    "P90 | Storm",
    "P90 | Sunset Lily",
    "P90 | Teardown",
    "P90 | Tiger Pit",
    "P90 | Traction",
    "P90 | Vent Rush",
    "P90 | Verdant Growth",
    "P90 | Virus",
    "PP-Bizon | Anolis",
    "PP-Bizon | Antique",
    "PP-Bizon | Bamboo Print",
    "PP-Bizon | Blue Streak",
    "PP-Bizon | Brass",
    "PP-Bizon | Breaker Box",
    "PP-Bizon | Candy Apple",
    "PP-Bizon | Carbon Fiber",
    "PP-Bizon | Chemical Green",
    "PP-Bizon | Cobalt Halftone",
    "PP-Bizon | Embargo",
    "PP-Bizon | Facility Sketch",
    "PP-Bizon | Forest Leaves",
    "PP-Bizon | Fuel Rod",
    "PP-Bizon | Harvester",
    "PP-Bizon | High Roller",
    "PP-Bizon | Irradiated Alert",
    "PP-Bizon | Judgement of Anubis",
    "PP-Bizon | Jungle Slipstream",
    "PP-Bizon | Lumen",
    "PP-Bizon | Modern Hunter",
    "PP-Bizon | Night Ops",
    "PP-Bizon | Night Riot",
    "PP-Bizon | Osiris",
    "PP-Bizon | Photic Zone",
    "PP-Bizon | Runic",
    "PP-Bizon | Rust Coat",
    "PP-Bizon | Sand Dashed",
    "PP-Bizon | Seabird",
    "PP-Bizon | Space Cat",
    "PP-Bizon | Urban Dashed",
    "PP-Bizon | Water Sigil",
    "R8 Revolver | Amber Fade",
    "R8 Revolver | Banana Cannon",
    "R8 Revolver | Blaze",
    "R8 Revolver | Bone Forged",
    "R8 Revolver | Bone Mask",
    "R8 Revolver | Canal Spray",
    "R8 Revolver | Crazy 8",
    "R8 Revolver | Crimson Web",
    "R8 Revolver | Desert Brush",
    "R8 Revolver | Fade",
    "R8 Revolver | Grip",
    "R8 Revolver | Inlay",
    "R8 Revolver | Junk Yard",
    "R8 Revolver | Llama Cannon",
    "R8 Revolver | Memento",
    "R8 Revolver | Night",
    "R8 Revolver | Nitro",
    "R8 Revolver | Phoenix Marker",
    "R8 Revolver | Reboot",
    "R8 Revolver | Survivalist",
    "SCAR-20 | Army Sheen",
    "SCAR-20 | Assault",
    "SCAR-20 | Bloodsport",
    "SCAR-20 | Blueprint",
    "SCAR-20 | Brass",
    "SCAR-20 | Carbon Fiber",
    "SCAR-20 | Cardiac",
    "SCAR-20 | Contractor",
    "SCAR-20 | Crimson Web",
    "SCAR-20 | Cyrex",
    "SCAR-20 | Emerald",
    "SCAR-20 | Enforcer",
    "SCAR-20 | Fragments",
    "SCAR-20 | Green Marine",
    "SCAR-20 | Grotto",
    "SCAR-20 | Jungle Slipstream",
    "SCAR-20 | Magna Carta",
    "SCAR-20 | Outbreak",
    "SCAR-20 | Palm",
    "SCAR-20 | Poultrygeist",
    "SCAR-20 | Powercore",
    "SCAR-20 | Sand Mesh",
    "SCAR-20 | Splash Jam",
    "SCAR-20 | Stone Mosaico",
    "SCAR-20 | Storm",
    "SCAR-20 | Torn",
    "SG 553 | Aerial",
    "SG 553 | Aloha",
    "SG 553 | Anodized Navy",
    "SG 553 | Army Sheen",
    "SG 553 | Atlas",
    "SG 553 | Barricade",
    "SG 553 | Bleached",
    "SG 553 | Bulldozer",
    "SG 553 | Candy Apple",
    "SG 553 | Colony IV",
    "SG 553 | Cyberforce",
    "SG 553 | Cyrex",
    "SG 553 | Damascus Steel",
    "SG 553 | Danger Close",
    "SG 553 | Darkwing",
    "SG 553 | Desert Blossom",
    "SG 553 | Dragon Tech",
    "SG 553 | Fallout Warning",
    "SG 553 | Gator Mesh",
    "SG 553 | Hazard Pay",
    "SG 553 | Heavy Metal",
    "SG 553 | Hypnotic",
    "SG 553 | Integrale",
    "SG 553 | Lush Ruins",
    "SG 553 | Ol&#39 Rusty",
    "SG 553 | Phantom",
    "SG 553 | Tiger Moth",
    "SG 553 | Tornado",
    "SG 553 | Traveler",
    "SG 553 | Triarch",
    "SG 553 | Ultraviolet",
    "SG 553 | Wave Spray",
    "SG 553 | Waves Perforated",
    "SSG 08 | Abyss",
    "SSG 08 | Acid Fade",
    "SSG 08 | Azure Glyph",
    "SSG 08 | Big Iron",
    "SSG 08 | Blood in the Water",
    "SSG 08 | Blue Spruce",
    "SSG 08 | Carbon Fiber",
    "SSG 08 | Death Strike",
    "SSG 08 | Death&#39s Head",
    "SSG 08 | Detour",
    "SSG 08 | Dragonfire",
    "SSG 08 | Fever Dream",
    "SSG 08 | Ghost Crusader",
    "SSG 08 | Hand Brake",
    "SSG 08 | Jungle Dashed",
    "SSG 08 | Lichen Dashed",
    "SSG 08 | Mainframe 001",
    "SSG 08 | Mayan Dreams",
    "SSG 08 | Necropos",
    "SSG 08 | Orange Filigree",
    "SSG 08 | Parallax",
    "SSG 08 | Prey",
    "SSG 08 | Red Stone",
    "SSG 08 | Sand Dune",
    "SSG 08 | Sea Calico",
    "SSG 08 | Spring Twilly",
    "SSG 08 | Threat Detected",
    "SSG 08 | Tropical Storm",
    "SSG 08 | Turbo Peek",
    "Sawed-Off | Amber Fade",
    "Sawed-Off | Apocalypto",
    "Sawed-Off | Bamboo Shadow",
    "Sawed-Off | Black Sand",
    "Sawed-Off | Brake Light",
    "Sawed-Off | Clay Ambush",
    "Sawed-Off | Copper",
    "Sawed-Off | Devourer",
    "Sawed-Off | First Class",
    "Sawed-Off | Forest DDPAT",
    "Sawed-Off | Full Stop",
    "Sawed-Off | Highwayman",
    "Sawed-Off | Irradiated Alert",
    "Sawed-Off | Jungle Thicket",
    "Sawed-Off | Kiss♥Love",
    "Sawed-Off | Limelight",
    "Sawed-Off | Morris",
    "Sawed-Off | Mosaico",
    "Sawed-Off | Orange DDPAT",
    "Sawed-Off | Origami",
    "Sawed-Off | Parched",
    "Sawed-Off | Rust Coat",
    "Sawed-Off | Sage Spray",
    "Sawed-Off | Serenity",
    "Sawed-Off | Snake Camo",
    "Sawed-Off | Spirit Board",
    "Sawed-Off | The Kraken",
    "Sawed-Off | Wasteland Princess",
    "Sawed-Off | Yorick",
    "Sawed-Off | Zander",
    "Tec-9 | Army Mesh",
    "Tec-9 | Avalanche",
    "Tec-9 | Bamboo Forest",
    "Tec-9 | Bamboozle",
    "Tec-9 | Blast From the Past",
    "Tec-9 | Blue Titanium",
    "Tec-9 | Brass",
    "Tec-9 | Brother",
    "Tec-9 | Cracked Opal",
    "Tec-9 | Cut Out",
    "Tec-9 | Decimator",
    "Tec-9 | Flash Out",
    "Tec-9 | Fuel Injector",
    "Tec-9 | Groundwater",
    "Tec-9 | Hades",
    "Tec-9 | Ice Cap",
    "Tec-9 | Isaac",
    "Tec-9 | Jambiya",
    "Tec-9 | Mummy&#39s Rot",
    "Tec-9 | Nuclear Threat",
    "Tec-9 | Orange Murano",
    "Tec-9 | Ossified",
    "Tec-9 | Phoenix Chalk",
    "Tec-9 | Re-Entry",
    "Tec-9 | Rebel",
    "Tec-9 | Red Quartz",
    "Tec-9 | Remote Control",
    "Tec-9 | Rust Leaf",
    "Tec-9 | Safety Net",
    "Tec-9 | Snek-9",
    "Tec-9 | Terrace",
    "Tec-9 | Titanium Bit",
    "Tec-9 | Tornado",
    "Tec-9 | Toxic",
    "Tec-9 | Urban DDPAT",
    "Tec-9 | VariCamo",
    "UMP-45 | Arctic Wolf",
    "UMP-45 | Blaze",
    "UMP-45 | Bone Pile",
    "UMP-45 | Briefing",
    "UMP-45 | Caramel",
    "UMP-45 | Carbon Fiber",
    "UMP-45 | Corporal",
    "UMP-45 | Crime Scene",
    "UMP-45 | Day Lily",
    "UMP-45 | Delusion",
    "UMP-45 | Exposure",
    "UMP-45 | Facility Dark",
    "UMP-45 | Fade",
    "UMP-45 | Fallout Warning",
    "UMP-45 | Full Stop",
    "UMP-45 | Gold Bismuth",
    "UMP-45 | Gunsmoke",
    "UMP-45 | Houndstooth",
    "UMP-45 | Indigo",
    "UMP-45 | Labyrinth",
    "UMP-45 | Mechanism",
    "UMP-45 | Metal Flowers",
    "UMP-45 | Minotaur&#39s Labyrinth",
    "UMP-45 | Momentum",
    "UMP-45 | Moonrise",
    "UMP-45 | Mudder",
    "UMP-45 | Oscillator",
    "UMP-45 | Plastique",
    "UMP-45 | Primal Saber",
    "UMP-45 | Riot",
    "UMP-45 | Roadblock",
    "UMP-45 | Scaffold",
    "UMP-45 | Scorched",
    "UMP-45 | Urban DDPAT",
    "UMP-45 | Wild Child",
    "USP-S | Ancient Visions",
    "USP-S | Black Lotus",
    "USP-S | Blood Tiger",
    "USP-S | Blueprint",
    "USP-S | Business Class",
    "USP-S | Caiman",
    "USP-S | Check Engine",
    "USP-S | Cortex",
    "USP-S | Cyrex",
    "USP-S | Desert Tactical",
    "USP-S | Flashback",
    "USP-S | Forest Leaves",
    "USP-S | Guardian",
    "USP-S | Kill Confirmed",
    "USP-S | Lead Conduit",
    "USP-S | Monster Mashup",
    "USP-S | Neo-Noir",
    "USP-S | Night Ops",
    "USP-S | Orange Anolis",
    "USP-S | Orion",
    "USP-S | Overgrowth",
    "USP-S | Para Green",
    "USP-S | Pathfinder",
    "USP-S | Printstream",
    "USP-S | Purple DDPAT",
    "USP-S | Road Rash",
    "USP-S | Royal Blue",
    "USP-S | Serum",
    "USP-S | Stainless",
    "USP-S | Target Acquired",
    "USP-S | The Traitor",
    "USP-S | Ticket to Hell",
    "USP-S | Torque",
    "USP-S | Whiteout",
    "XM1014 | Ancient Lore",
    "XM1014 | Banana Leaf",
    "XM1014 | Black Tie",
    "XM1014 | Blaze Orange",
    "XM1014 | Blue Spruce",
    "XM1014 | Blue Steel",
    "XM1014 | Blue Tire",
    "XM1014 | Bone Machine",
    "XM1014 | CaliCamo",
    "XM1014 | Charter",
    "XM1014 | Elegant Vines",
    "XM1014 | Entombed",
    "XM1014 | Fallout Warning",
    "XM1014 | Frost Borre",
    "XM1014 | Grassland",
    "XM1014 | Heaven Guard",
    "XM1014 | Hieroglyph",
    "XM1014 | Jungle",
    "XM1014 | Oxide Blaze",
    "XM1014 | Quicksilver",
    "XM1014 | Red Leather",
    "XM1014 | Scumbria",
    "XM1014 | Seasons",
    "XM1014 | Slipstream",
    "XM1014 | Teclu Burner",
    "XM1014 | Tranquility",
    "XM1014 | Urban Perforated",
    "XM1014 | VariCamo Blue",
    "XM1014 | Watchdog",
    "XM1014 | XOXO",
    "XM1014 | Ziggy",
    "XM1014 | Zombie Offensive",
    "★ Bayonet | Autotronic",
    "★ Bayonet | Black Laminate",
    "★ Bayonet | Blue Steel",
    "★ Bayonet | Boreal Forest",
    "★ Bayonet | Bright Water",
    "★ Bayonet | Case Hardened",
    "★ Bayonet | Crimson Web",
    "★ Bayonet | Damascus Steel",
    "★ Bayonet | Doppler",
    "★ Bayonet | Fade",
    "★ Bayonet | Forest DDPAT",
    "★ Bayonet | Freehand",
    "★ Bayonet | Gamma Doppler",
    "★ Bayonet | Lore",
    "★ Bayonet | Marble Fade",
    "★ Bayonet | Night",
    "★ Bayonet | Safari Mesh",
    "★ Bayonet | Scorched",
    "★ Bayonet | Slaughter",
    "★ Bayonet | Stained",
    "★ Bayonet | Tiger Tooth",
    "★ Bayonet | Ultraviolet",
    "★ Bayonet | Urban Masked",
    "★ Bloodhound Gloves | Bronzed",
    "★ Bloodhound Gloves | Charred",
    "★ Bloodhound Gloves | Guerrilla",
    "★ Bloodhound Gloves | Snakebite",
    "★ Bowie Knife | Autotronic",
    "★ Bowie Knife | Black Laminate",
    "★ Bowie Knife | Blue Steel",
    "★ Bowie Knife | Boreal Forest",
    "★ Bowie Knife | Bright Water",
    "★ Bowie Knife | Case Hardened",
    "★ Bowie Knife | Crimson Web",
    "★ Bowie Knife | Damascus Steel",
    "★ Bowie Knife | Doppler",
    "★ Bowie Knife | Fade",
    "★ Bowie Knife | Forest DDPAT",
    "★ Bowie Knife | Freehand",
    "★ Bowie Knife | Gamma Doppler",
    "★ Bowie Knife | Lore",
    "★ Bowie Knife | Marble Fade",
    "★ Bowie Knife | Night",
    "★ Bowie Knife | Safari Mesh",
    "★ Bowie Knife | Scorched",
    "★ Bowie Knife | Slaughter",
    "★ Bowie Knife | Stained",
    "★ Bowie Knife | Tiger Tooth",
    "★ Bowie Knife | Ultraviolet",
    "★ Bowie Knife | Urban Masked",
    "★ Broken Fang Gloves | Jade",
    "★ Broken Fang Gloves | Needle Point",
    "★ Broken Fang Gloves | Unhinged",
    "★ Broken Fang Gloves | Yellow-banded",
    "★ Butterfly Knife | Autotronic",
    "★ Butterfly Knife | Black Laminate",
    "★ Butterfly Knife | Blue Steel",
    "★ Butterfly Knife | Boreal Forest",
    "★ Butterfly Knife | Bright Water",
    "★ Butterfly Knife | Case Hardened",
    "★ Butterfly Knife | Crimson Web",
    "★ Butterfly Knife | Damascus Steel",
    "★ Butterfly Knife | Doppler",
    "★ Butterfly Knife | Fade",
    "★ Butterfly Knife | Forest DDPAT",
    "★ Butterfly Knife | Freehand",
    "★ Butterfly Knife | Gamma Doppler",
    "★ Butterfly Knife | Lore",
    "★ Butterfly Knife | Marble Fade",
    "★ Butterfly Knife | Night",
    "★ Butterfly Knife | Safari Mesh",
    "★ Butterfly Knife | Scorched",
    "★ Butterfly Knife | Slaughter",
    "★ Butterfly Knife | Stained",
    "★ Butterfly Knife | Tiger Tooth",
    "★ Butterfly Knife | Ultraviolet",
    "★ Butterfly Knife | Urban Masked",
    "★ Classic Knife | Blue Steel",
    "★ Classic Knife | Boreal Forest",
    "★ Classic Knife | Case Hardened",
    "★ Classic Knife | Crimson Web",
    "★ Classic Knife | Fade",
    "★ Classic Knife | Forest DDPAT",
    "★ Classic Knife | Night Stripe",
    "★ Classic Knife | Safari Mesh",
    "★ Classic Knife | Scorched",
    "★ Classic Knife | Slaughter",
    "★ Classic Knife | Stained",
    "★ Classic Knife | Urban Masked",
    "★ Driver Gloves | Black Tie",
    "★ Driver Gloves | Convoy",
    "★ Driver Gloves | Crimson Weave",
    "★ Driver Gloves | Diamondback",
    "★ Driver Gloves | Imperial Plaid",
    "★ Driver Gloves | King Snake",
    "★ Driver Gloves | Lunar Weave",
    "★ Driver Gloves | Overtake",
    "★ Driver Gloves | Queen Jaguar",
    "★ Driver Gloves | Racing Green",
    "★ Driver Gloves | Rezan the Red",
    "★ Driver Gloves | Snow Leopard",
    "★ Falchion Knife | Autotronic",
    "★ Falchion Knife | Black Laminate",
    "★ Falchion Knife | Blue Steel",
    "★ Falchion Knife | Boreal Forest",
    "★ Falchion Knife | Bright Water",
    "★ Falchion Knife | Case Hardened",
    "★ Falchion Knife | Crimson Web",
    "★ Falchion Knife | Damascus Steel",
    "★ Falchion Knife | Doppler",
    "★ Falchion Knife | Fade",
    "★ Falchion Knife | Forest DDPAT",
    "★ Falchion Knife | Freehand",
    "★ Falchion Knife | Gamma Doppler",
    "★ Falchion Knife | Lore",
    "★ Falchion Knife | Marble Fade",
    "★ Falchion Knife | Night",
    "★ Falchion Knife | Safari Mesh",
    "★ Falchion Knife | Scorched",
    "★ Falchion Knife | Slaughter",
    "★ Falchion Knife | Stained",
    "★ Falchion Knife | Tiger Tooth",
    "★ Falchion Knife | Ultraviolet",
    "★ Falchion Knife | Urban Masked",
    "★ Flip Knife | Autotronic",
    "★ Flip Knife | Black Laminate",
    "★ Flip Knife | Blue Steel",
    "★ Flip Knife | Boreal Forest",
    "★ Flip Knife | Bright Water",
    "★ Flip Knife | Case Hardened",
    "★ Flip Knife | Crimson Web",
    "★ Flip Knife | Damascus Steel",
    "★ Flip Knife | Doppler",
    "★ Flip Knife | Fade",
    "★ Flip Knife | Forest DDPAT",
    "★ Flip Knife | Freehand",
    "★ Flip Knife | Gamma Doppler",
    "★ Flip Knife | Lore",
    "★ Flip Knife | Marble Fade",
    "★ Flip Knife | Night",
    "★ Flip Knife | Safari Mesh",
    "★ Flip Knife | Scorched",
    "★ Flip Knife | Slaughter",
    "★ Flip Knife | Stained",
    "★ Flip Knife | Tiger Tooth",
    "★ Flip Knife | Ultraviolet",
    "★ Flip Knife | Urban Masked",
    "★ Gut Knife | Autotronic",
    "★ Gut Knife | Black Laminate",
    "★ Gut Knife | Blue Steel",
    "★ Gut Knife | Boreal Forest",
    "★ Gut Knife | Bright Water",
    "★ Gut Knife | Case Hardened",
    "★ Gut Knife | Crimson Web",
    "★ Gut Knife | Damascus Steel",
    "★ Gut Knife | Doppler",
    "★ Gut Knife | Fade",
    "★ Gut Knife | Forest DDPAT",
    "★ Gut Knife | Freehand",
    "★ Gut Knife | Gamma Doppler",
    "★ Gut Knife | Lore",
    "★ Gut Knife | Marble Fade",
    "★ Gut Knife | Night",
    "★ Gut Knife | Safari Mesh",
    "★ Gut Knife | Scorched",
    "★ Gut Knife | Slaughter",
    "★ Gut Knife | Stained",
    "★ Gut Knife | Tiger Tooth",
    "★ Gut Knife | Ultraviolet",
    "★ Gut Knife | Urban Masked",
    "★ Hand Wraps | Arboreal",
    "★ Hand Wraps | Badlands",
    "★ Hand Wraps | CAUTION!",
    "★ Hand Wraps | Cobalt Skulls",
    "★ Hand Wraps | Constrictor",
    "★ Hand Wraps | Desert Shamagh",
    "★ Hand Wraps | Duct Tape",
    "★ Hand Wraps | Giraffe",
    "★ Hand Wraps | Leather",
    "★ Hand Wraps | Overprint",
    "★ Hand Wraps | Slaughter",
    "★ Hand Wraps | Spruce DDPAT",
    "★ Huntsman Knife | Autotronic",
    "★ Huntsman Knife | Black Laminate",
    "★ Huntsman Knife | Blue Steel",
    "★ Huntsman Knife | Boreal Forest",
    "★ Huntsman Knife | Bright Water",
    "★ Huntsman Knife | Case Hardened",
    "★ Huntsman Knife | Crimson Web",
    "★ Huntsman Knife | Damascus Steel",
    "★ Huntsman Knife | Doppler",
    "★ Huntsman Knife | Fade",
    "★ Huntsman Knife | Forest DDPAT",
    "★ Huntsman Knife | Freehand",
    "★ Huntsman Knife | Gamma Doppler",
    "★ Huntsman Knife | Lore",
    "★ Huntsman Knife | Marble Fade",
    "★ Huntsman Knife | Night",
    "★ Huntsman Knife | Safari Mesh",
    "★ Huntsman Knife | Scorched",
    "★ Huntsman Knife | Slaughter",
    "★ Huntsman Knife | Stained",
    "★ Huntsman Knife | Tiger Tooth",
    "★ Huntsman Knife | Ultraviolet",
    "★ Huntsman Knife | Urban Masked",
    "★ Hydra Gloves | Case Hardened",
    "★ Hydra Gloves | Emerald",
    "★ Hydra Gloves | Mangrove",
    "★ Hydra Gloves | Rattler",
    "★ Karambit | Autotronic",
    "★ Karambit | Black Laminate",
    "★ Karambit | Blue Steel",
    "★ Karambit | Boreal Forest",
    "★ Karambit | Bright Water",
    "★ Karambit | Case Hardened",
    "★ Karambit | Crimson Web",
    "★ Karambit | Damascus Steel",
    "★ Karambit | Doppler",
    "★ Karambit | Fade",
    "★ Karambit | Forest DDPAT",
    "★ Karambit | Freehand",
    "★ Karambit | Gamma Doppler",
    "★ Karambit | Lore",
    "★ Karambit | Marble Fade",
    "★ Karambit | Night",
    "★ Karambit | Safari Mesh",
    "★ Karambit | Scorched",
    "★ Karambit | Slaughter",
    "★ Karambit | Stained",
    "★ Karambit | Tiger Tooth",
    "★ Karambit | Ultraviolet",
    "★ Karambit | Urban Masked",
    "★ M9 Bayonet | Autotronic",
    "★ M9 Bayonet | Black Laminate",
    "★ M9 Bayonet | Blue Steel",
    "★ M9 Bayonet | Boreal Forest",
    "★ M9 Bayonet | Bright Water",
    "★ M9 Bayonet | Case Hardened",
    "★ M9 Bayonet | Crimson Web",
    "★ M9 Bayonet | Damascus Steel",
    "★ M9 Bayonet | Doppler",
    "★ M9 Bayonet | Fade",
    "★ M9 Bayonet | Forest DDPAT",
    "★ M9 Bayonet | Freehand",
    "★ M9 Bayonet | Gamma Doppler",
    "★ M9 Bayonet | Lore",
    "★ M9 Bayonet | Marble Fade",
    "★ M9 Bayonet | Night",
    "★ M9 Bayonet | Safari Mesh",
    "★ M9 Bayonet | Scorched",
    "★ M9 Bayonet | Slaughter",
    "★ M9 Bayonet | Stained",
    "★ M9 Bayonet | Tiger Tooth",
    "★ M9 Bayonet | Ultraviolet",
    "★ M9 Bayonet | Urban Masked",
    "★ Moto Gloves | 3rd Commando Company",
    "★ Moto Gloves | Blood Pressure",
    "★ Moto Gloves | Boom!",
    "★ Moto Gloves | Cool Mint",
    "★ Moto Gloves | Eclipse",
    "★ Moto Gloves | Finish Line",
    "★ Moto Gloves | POW!",
    "★ Moto Gloves | Polygon",
    "★ Moto Gloves | Smoke Out",
    "★ Moto Gloves | Spearmint",
    "★ Moto Gloves | Transport",
    "★ Moto Gloves | Turtle",
    "★ Navaja Knife | Blue Steel",
    "★ Navaja Knife | Boreal Forest",
    "★ Navaja Knife | Case Hardened",
    "★ Navaja Knife | Crimson Web",
    "★ Navaja Knife | Damascus Steel",
    "★ Navaja Knife | Doppler",
    "★ Navaja Knife | Fade",
    "★ Navaja Knife | Forest DDPAT",
    "★ Navaja Knife | Marble Fade",
    "★ Navaja Knife | Night Stripe",
    "★ Navaja Knife | Safari Mesh",
    "★ Navaja Knife | Scorched",
    "★ Navaja Knife | Slaughter",
    "★ Navaja Knife | Stained",
    "★ Navaja Knife | Tiger Tooth",
    "★ Navaja Knife | Ultraviolet",
    "★ Navaja Knife | Urban Masked",
    "★ Nomad Knife | Blue Steel",
    "★ Nomad Knife | Boreal Forest",
    "★ Nomad Knife | Case Hardened",
    "★ Nomad Knife | Crimson Web",
    "★ Nomad Knife | Fade",
    "★ Nomad Knife | Forest DDPAT",
    "★ Nomad Knife | Night Stripe",
    "★ Nomad Knife | Safari Mesh",
    "★ Nomad Knife | Scorched",
    "★ Nomad Knife | Slaughter",
    "★ Nomad Knife | Stained",
    "★ Nomad Knife | Urban Masked",
    "★ Paracord Knife | Blue Steel",
    "★ Paracord Knife | Boreal Forest",
    "★ Paracord Knife | Case Hardened",
    "★ Paracord Knife | Crimson Web",
    "★ Paracord Knife | Fade",
    "★ Paracord Knife | Forest DDPAT",
    "★ Paracord Knife | Night Stripe",
    "★ Paracord Knife | Safari Mesh",
    "★ Paracord Knife | Scorched",
    "★ Paracord Knife | Slaughter",
    "★ Paracord Knife | Stained",
    "★ Paracord Knife | Urban Masked",
    "★ Shadow Daggers | Autotronic",
    "★ Shadow Daggers | Black Laminate",
    "★ Shadow Daggers | Blue Steel",
    "★ Shadow Daggers | Boreal Forest",
    "★ Shadow Daggers | Bright Water",
    "★ Shadow Daggers | Case Hardened",
    "★ Shadow Daggers | Crimson Web",
    "★ Shadow Daggers | Damascus Steel",
    "★ Shadow Daggers | Doppler",
    "★ Shadow Daggers | Fade",
    "★ Shadow Daggers | Forest DDPAT",
    "★ Shadow Daggers | Freehand",
    "★ Shadow Daggers | Gamma Doppler",
    "★ Shadow Daggers | Lore",
    "★ Shadow Daggers | Marble Fade",
    "★ Shadow Daggers | Night",
    "★ Shadow Daggers | Safari Mesh",
    "★ Shadow Daggers | Scorched",
    "★ Shadow Daggers | Slaughter",
    "★ Shadow Daggers | Stained",
    "★ Shadow Daggers | Tiger Tooth",
    "★ Shadow Daggers | Ultraviolet",
    "★ Shadow Daggers | Urban Masked",
    "★ Skeleton Knife | Blue Steel",
    "★ Skeleton Knife | Boreal Forest",
    "★ Skeleton Knife | Case Hardened",
    "★ Skeleton Knife | Crimson Web",
    "★ Skeleton Knife | Fade",
    "★ Skeleton Knife | Forest DDPAT",
    "★ Skeleton Knife | Night Stripe",
    "★ Skeleton Knife | Safari Mesh",
    "★ Skeleton Knife | Scorched",
    "★ Skeleton Knife | Slaughter",
    "★ Skeleton Knife | Stained",
    "★ Skeleton Knife | Urban Masked",
    "★ Specialist Gloves | Buckshot",
    "★ Specialist Gloves | Crimson Kimono",
    "★ Specialist Gloves | Crimson Web",
    "★ Specialist Gloves | Emerald Web",
    "★ Specialist Gloves | Fade",
    "★ Specialist Gloves | Field Agent",
    "★ Specialist Gloves | Forest DDPAT",
    "★ Specialist Gloves | Foundation",
    "★ Specialist Gloves | Lt. Commander",
    "★ Specialist Gloves | Marble Fade",
    "★ Specialist Gloves | Mogul",
    "★ Specialist Gloves | Tiger Strike",
    "★ Sport Gloves | Amphibious",
    "★ Sport Gloves | Arid",
    "★ Sport Gloves | Big Game",
    "★ Sport Gloves | Bronze Morph",
    "★ Sport Gloves | Hedge Maze",
    "★ Sport Gloves | Nocts",
    "★ Sport Gloves | Omega",
    "★ Sport Gloves | Pandora&#39s Box",
    "★ Sport Gloves | Scarlet Shamagh",
    "★ Sport Gloves | Slingshot",
    "★ Sport Gloves | Superconductor",
    "★ Sport Gloves | Vice",
    "★ Stiletto Knife | Blue Steel",
    "★ Stiletto Knife | Boreal Forest",
    "★ Stiletto Knife | Case Hardened",
    "★ Stiletto Knife | Crimson Web",
    "★ Stiletto Knife | Damascus Steel",
    "★ Stiletto Knife | Doppler",
    "★ Stiletto Knife | Fade",
    "★ Stiletto Knife | Forest DDPAT",
    "★ Stiletto Knife | Marble Fade",
    "★ Stiletto Knife | Night Stripe",
    "★ Stiletto Knife | Safari Mesh",
    "★ Stiletto Knife | Scorched",
    "★ Stiletto Knife | Slaughter",
    "★ Stiletto Knife | Stained",
    "★ Stiletto Knife | Tiger Tooth",
    "★ Stiletto Knife | Ultraviolet",
    "★ Stiletto Knife | Urban Masked",
    "★ Survival Knife | Blue Steel",
    "★ Survival Knife | Boreal Forest",
    "★ Survival Knife | Case Hardened",
    "★ Survival Knife | Crimson Web",
    "★ Survival Knife | Fade",
    "★ Survival Knife | Forest DDPAT",
    "★ Survival Knife | Night Stripe",
    "★ Survival Knife | Safari Mesh",
    "★ Survival Knife | Scorched",
    "★ Survival Knife | Slaughter",
    "★ Survival Knife | Stained",
    "★ Survival Knife | Urban Masked",
    "★ Talon Knife | Blue Steel",
    "★ Talon Knife | Boreal Forest",
    "★ Talon Knife | Case Hardened",
    "★ Talon Knife | Crimson Web",
    "★ Talon Knife | Damascus Steel",
    "★ Talon Knife | Doppler",
    "★ Talon Knife | Fade",
    "★ Talon Knife | Forest DDPAT",
    "★ Talon Knife | Marble Fade",
    "★ Talon Knife | Night Stripe",
    "★ Talon Knife | Safari Mesh",
    "★ Talon Knife | Scorched",
    "★ Talon Knife | Slaughter",
    "★ Talon Knife | Stained",
    "★ Talon Knife | Tiger Tooth",
    "★ Talon Knife | Ultraviolet",
    "★ Talon Knife | Urban Masked",
    "★ Ursus Knife | Blue Steel",
    "★ Ursus Knife | Boreal Forest",
    "★ Ursus Knife | Case Hardened",
    "★ Ursus Knife | Crimson Web",
    "★ Ursus Knife | Damascus Steel",
    "★ Ursus Knife | Doppler",
    "★ Ursus Knife | Fade",
    "★ Ursus Knife | Forest DDPAT",
    "★ Ursus Knife | Marble Fade",
    "★ Ursus Knife | Night Stripe",
    "★ Ursus Knife | Safari Mesh",
    "★ Ursus Knife | Scorched",
    "★ Ursus Knife | Slaughter",
    "★ Ursus Knife | Stained",
    "★ Ursus Knife | Tiger Tooth",
    "★ Ursus Knife | Ultraviolet",
    "★ Ursus Knife | Urban Masked",
];

import { NextResponse } from "next/server";

export async function GET() {
    return NextResponse.json(skinData);
}
